# Generated by Django 3.0.4 on 2020-04-15 10:14

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields
import pretix.base.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0150_auto_20200401_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
                ('title', i18nfield.fields.I18nCharField()),
                ('text', i18nfield.fields.I18nTextField()),
                ('all_products', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event')),
                ('limit_products', models.ManyToManyField(to='pretixbase.Item')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
